server:
  port: 8002

#对应的Eureka的信息
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
       defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-dept8002
    prefer-ip-address: true     #访问路径可以显示IP地址



