server:
  port: 8001


spring:
  application:
    name: springcloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  type-aliases-package: org.myself.pojo
  mapper-locations: classpath:org/myself/mapper/*Mapper.xml          #mybatis配置-别名包扫描


#对应的Eureka的信息
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
       defaultZone: http://localhost:7001/eureka
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: springcloud_demo
  company.name: www.myself.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

